### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Drymay** [TotkMods/Totk.ZStdTool#5]
System.TypeInitializationException: The type initializer for 'Totk.ZStdTool.Helpers.ZStdHelper' threw an exception.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Heitor\AppData\Roaming\yuzu\dump\0100F2C0115B6000\Pack\ZsDic.pack.zs'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at Totk.ZStdTool.Helpers.ZStdHelper..cctor() in D:\a\Totk.ZStdTool\Totk.ZStdTool\src\Helpers\ZStdHelper.cs:line 18
   --- End of inner exception stack trace ---
   at Totk.ZStdTool.Helpers.ZStdHelper.Decompress(String file) in D:\a\Totk.ZStdTool\Totk.ZStdTool\src\Helpers\ZStdHelper.cs:line 32
   at Totk.ZStdTool.ViewModels.ShellViewModel.Decompress() in D:\a\Totk.ZStdTool\Totk.ZStdTool\src\ViewModels\ShellViewModel.cs:line 76

**Comment by Drymay** [comment]
trying to unpack files with possible text! give me this error, any help?

**Comment by Drymay** [comment]
Forget, this error fix , put path correct ! thx Dev and sorry!

**Comment by SvardXI** [comment]
Getting the same filepath error in most recent version. Tried dragging and dropping, and tried browsing manually.

System.TypeInitializationException: The type initializer for 'Totk.ZStdTool.Helpers.ZStdHelper' threw an exception.
 ---> System.IO.FileNotFoundException: Could not find file 'G:\Games\SwitchHAX\Zelda - Tears of the Kingdom\(0100F2C0115B6000) (BASE)\Pack\ZsDic.pack.zs'.
File name: 'G:\Games\SwitchHAX\Zelda - Tears of the Kingdom\(0100F2C0115B6000) (BASE)\Pack\ZsDic.pack.zs'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at Totk.ZStdTool.Helpers.ZStdHelper..cctor() in D:\a\Totk.ZStdTool\Totk.ZStdTool\src\Helpers\ZStdHelper.cs:line 18
   --- End of inner exception stack trace ---
   at Totk.ZStdTool.Helpers.ZStdHelper.Decompress(String file) in D:\a\Totk.ZStdTool\Totk.ZStdTool\src\Helpers\ZStdHelper.cs:line 32
   at Totk.ZStdTool.ViewModels.ShellViewModel.Decompress() in D:\a\Totk.ZStdTool\Totk.ZStdTool\src\ViewModels\ShellViewModel.cs:line 76
   
Game path is set:
![image](https://github.com/TotkMods/Totk.ZStdTool/assets/8410417/31796c3e-2ca9-4523-87cd-bfc75c94ada0)

.NET 7 is also installed:
![image](https://github.com/TotkMods/Totk.ZStdTool/assets/8410417/7b5e168f-5af3-4bbd-8003-6d3d1add5f52)

**Comment by ArchLeaders** [comment]
Game path is wrong, make sure it points to the folder with the actual files in it, not a `romfs` folder.

**Comment by sharkiller** [comment]
@ArchLeaders what is the gamepath? nca files? nsp? xci? i cant get it to work

**Comment by SvardXI** [comment]
Got it. Changed path to "G:\Games\SwitchHAX\Zelda - Tears of the Kingdom\0100F2C0115B6000\romfs" in my case.

@sharkiller You need to dump the files from the game itself first, either using something like nxdumptool on the Switch, or using Yuzu to dump the XCI/NSP.

**Comment by sharkiller** [comment]
@SvardXI yeah i get it working too. i was confused because the other guy said "not a romfs folder" which is exactly where you need to point it...

**Comment by Drymay** [comment]
exactly, just put it in the correct folder that works, I'll close the topic. thank you all
